In [1]:
import pandas as pd

In [34]:
df = pd.read_excel("C:/Users/Mua/Downloads/cars.xlsx")
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,STRING,DOUBLE,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,CAT
1,Chevrolet Chevelle Malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US
2,Buick Skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US
3,Plymouth Satellite,18.0,8,318.0,150.0,3436.0,11.0,70,US
4,AMC Rebel SST,16.0,8,304.0,150.0,3433.0,12.0,70,US
...,...,...,...,...,...,...,...,...,...
402,Ford Mustang GL,27.0,4,140.0,86.0,2790.0,15.6,82,US
403,Volkswagen Pickup,44.0,4,97.0,52.0,2130.0,24.6,82,Europe
404,Dodge Rampage,32.0,4,135.0,84.0,2295.0,11.6,82,US
405,Ford Ranger,28.0,4,120.0,79.0,2625.0,18.6,82,US
406,Chevy S-10,31.0,4,119.0,82.0,2720.0,19.4,82,US

In [35]:
df.head(51)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,STRING,DOUBLE,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,CAT
1,Chevrolet Chevelle Malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US
2,Buick Skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US
3,Plymouth Satellite,18.0,8,318.0,150.0,3436.0,11.0,70,US
4,AMC Rebel SST,16.0,8,304.0,150.0,3433.0,12.0,70,US
5,Ford Torino,17.0,8,302.0,140.0,3449.0,10.5,70,US
6,Ford Galaxie 500,15.0,8,429.0,198.0,4341.0,10.0,70,US
7,Chevrolet Impala,14.0,8,454.0,220.0,4354.0,9.0,70,US
8,Plymouth Fury iii,14.0,8,440.0,215.0,4312.0,8.5,70,US
9,Pontiac Catalina,14.0,8,455.0,225.0,4425.0,10.0,70,US
10,AMC Ambassador DPL,15.0,8,390.0,190.0,3850.0,8.5,70,US
11,Citroen DS-21 Pallas,0,4,133.0,115.0,3090.0,17.5,70,Europe
12,Chevrolet Chevelle Concours (sw),0,8,350.0,165.0,4142.0,11.5,70,US
13,Ford Torino (sw),0,8,351.0,153.0,4034.0,11.0,70,US
14,Plymouth Satellite (sw),0,8,383.0,175.0,4166.0,10.5,70,US
15,AMC Rebel SST (sw),0,8,360.0,175.0,3850.0,11.0,70,US
16,Dodge Challenger SE,15.0,8,383.0,170.0,3563.0,10.0,70,US
17,Plymouth 'Cuda 340,14.0,8,340.0,160.0,3609.0,8.0,70,US
18,Ford Mustang Boss 302,0,8,302.0,140.0,3353.0,8.0,70,US
19,Chevrolet Monte Carlo,15.0,8,400.0,150.0,3761.0,9.5,70,US
20,Buick Estate Wagon (sw),14.0,8,455.0,225.0,3086.0,10.0,70,US
21,Toyota Corolla Mark ii,24.0,4,113.0,95.0,2372.0,15.0,70,Japan
22,Plymouth Duster,22.0,6,198.0,95.0,2833.0,15.5,70,US
23,AMC Hornet,18.0,6,199.0,97.0,2774.0,15.5,70,US
24,Ford Maverick,21.0,6,200.0,85.0,2587.0,16.0,70,US
25,Datsun PL510,27.0,4,97.0,88.0,2130.0,14.5,70,Japan
26,Volkswagen 1131 Deluxe Sedan,26.0,4,97.0,46.0,1835.0,20.5,70,Europe
27,Peugeot 504,25.0,4,110.0,87.0,2672.0,17.5,70,Europe
28,Audi 100 LS,24.0,4,107.0,90.0,2430.0,14.5,70,Europe
29,Saab 99e,25.0,4,104.0,95.0,2375.0,17.5,70,Europe
30,BMW 2002,26.0,4,121.0,113.0,2234.0,12.5,70,Europe
31,AMC Gremlin,21.0,6,199.0,90.0,2648.0,15.0,70,US
32,Ford F250,10.0,8,360.0,215.0,4615.0,14.0,70,US
33,Chevy C20,10.0,8,307.0,200.0,4376.0,15.0,70,US
34,Dodge D200,11.0,8,318.0,210.0,4382.0,13.5,70,US
35,Hi 1200D,9.0,8,304.0,193.0,4732.0,18.5,70,US
36,Datsun PL510,27.0,4,97.0,88.0,2130.0,14.5,71,Japan
37,Chevrolet Vega 2300,28.0,4,140.0,90.0,2264.0,15.5,71,US
38,Toyota Corolla,25.0,4,113.0,95.0,2228.0,14.0,71,Japan
39,Ford Pinto,25.0,4,98.0,0,2046.0,19.0,71,US
40,Volkswagen Super Beetle 117,0,4,97.0,48.0,1978.0,20.0,71,Europe
41,AMC Gremlin,19.0,6,232.0,100.0,2634.0,13.0,71,US
42,Plymouth Satellite Custom,16.0,6,225.0,105.0,3439.0,15.5,71,US
43,Chevrolet Chevelle Malibu,17.0,6,250.0,100.0,3329.0,15.5,71,US
44,Ford Torino 500,19.0,6,250.0,88.0,3302.0,15.5,71,US
45,AMC Matador,18.0,6,232.0,100.0,3288.0,15.5,71,US
46,Chevrolet Impala,14.0,8,350.0,165.0,4209.0,12.0,71,US
47,Pontiac Catalina Brougham,14.0,8,400.0,175.0,4464.0,11.5,71,US
48,Ford Galaxie 500,14.0,8,351.0,153.0,4154.0,13.5,71,US
49,Plymouth Fury iii,14.0,8,318.0,150.0,4096.0,13.0,71,US
50,Dodge Monaco (sw),12.0,8,383.0,180.0,4955.0,11.5,71,US

In [36]:
dff = df.head(51)
dff

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,STRING,DOUBLE,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,CAT
1,Chevrolet Chevelle Malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US
2,Buick Skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US
3,Plymouth Satellite,18.0,8,318.0,150.0,3436.0,11.0,70,US
4,AMC Rebel SST,16.0,8,304.0,150.0,3433.0,12.0,70,US
5,Ford Torino,17.0,8,302.0,140.0,3449.0,10.5,70,US
6,Ford Galaxie 500,15.0,8,429.0,198.0,4341.0,10.0,70,US
7,Chevrolet Impala,14.0,8,454.0,220.0,4354.0,9.0,70,US
8,Plymouth Fury iii,14.0,8,440.0,215.0,4312.0,8.5,70,US
9,Pontiac Catalina,14.0,8,455.0,225.0,4425.0,10.0,70,US
10,AMC Ambassador DPL,15.0,8,390.0,190.0,3850.0,8.5,70,US
11,Citroen DS-21 Pallas,0,4,133.0,115.0,3090.0,17.5,70,Europe
12,Chevrolet Chevelle Concours (sw),0,8,350.0,165.0,4142.0,11.5,70,US
13,Ford Torino (sw),0,8,351.0,153.0,4034.0,11.0,70,US
14,Plymouth Satellite (sw),0,8,383.0,175.0,4166.0,10.5,70,US
15,AMC Rebel SST (sw),0,8,360.0,175.0,3850.0,11.0,70,US
16,Dodge Challenger SE,15.0,8,383.0,170.0,3563.0,10.0,70,US
17,Plymouth 'Cuda 340,14.0,8,340.0,160.0,3609.0,8.0,70,US
18,Ford Mustang Boss 302,0,8,302.0,140.0,3353.0,8.0,70,US
19,Chevrolet Monte Carlo,15.0,8,400.0,150.0,3761.0,9.5,70,US
20,Buick Estate Wagon (sw),14.0,8,455.0,225.0,3086.0,10.0,70,US
21,Toyota Corolla Mark ii,24.0,4,113.0,95.0,2372.0,15.0,70,Japan
22,Plymouth Duster,22.0,6,198.0,95.0,2833.0,15.5,70,US
23,AMC Hornet,18.0,6,199.0,97.0,2774.0,15.5,70,US
24,Ford Maverick,21.0,6,200.0,85.0,2587.0,16.0,70,US
25,Datsun PL510,27.0,4,97.0,88.0,2130.0,14.5,70,Japan
26,Volkswagen 1131 Deluxe Sedan,26.0,4,97.0,46.0,1835.0,20.5,70,Europe
27,Peugeot 504,25.0,4,110.0,87.0,2672.0,17.5,70,Europe
28,Audi 100 LS,24.0,4,107.0,90.0,2430.0,14.5,70,Europe
29,Saab 99e,25.0,4,104.0,95.0,2375.0,17.5,70,Europe
30,BMW 2002,26.0,4,121.0,113.0,2234.0,12.5,70,Europe
31,AMC Gremlin,21.0,6,199.0,90.0,2648.0,15.0,70,US
32,Ford F250,10.0,8,360.0,215.0,4615.0,14.0,70,US
33,Chevy C20,10.0,8,307.0,200.0,4376.0,15.0,70,US
34,Dodge D200,11.0,8,318.0,210.0,4382.0,13.5,70,US
35,Hi 1200D,9.0,8,304.0,193.0,4732.0,18.5,70,US
36,Datsun PL510,27.0,4,97.0,88.0,2130.0,14.5,71,Japan
37,Chevrolet Vega 2300,28.0,4,140.0,90.0,2264.0,15.5,71,US
38,Toyota Corolla,25.0,4,113.0,95.0,2228.0,14.0,71,Japan
39,Ford Pinto,25.0,4,98.0,0,2046.0,19.0,71,US
40,Volkswagen Super Beetle 117,0,4,97.0,48.0,1978.0,20.0,71,Europe
41,AMC Gremlin,19.0,6,232.0,100.0,2634.0,13.0,71,US
42,Plymouth Satellite Custom,16.0,6,225.0,105.0,3439.0,15.5,71,US
43,Chevrolet Chevelle Malibu,17.0,6,250.0,100.0,3329.0,15.5,71,US
44,Ford Torino 500,19.0,6,250.0,88.0,3302.0,15.5,71,US
45,AMC Matador,18.0,6,232.0,100.0,3288.0,15.5,71,US
46,Chevrolet Impala,14.0,8,350.0,165.0,4209.0,12.0,71,US
47,Pontiac Catalina Brougham,14.0,8,400.0,175.0,4464.0,11.5,71,US
48,Ford Galaxie 500,14.0,8,351.0,153.0,4154.0,13.5,71,US
49,Plymouth Fury iii,14.0,8,318.0,150.0,4096.0,13.0,71,US
50,Dodge Monaco (sw),12.0,8,383.0,180.0,4955.0,11.5,71,US

In [12]:
dff.describe()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
count,51,51.0,51,51.0,51.0,51.0,51.0,51,51
unique,45,19.0,4,31.0,31.0,49.0,23.0,3,4
top,Chevrolet Chevelle Malibu,14.0,8,97.0,95.0,2130.0,15.5,70,US
freq,2,9.0,28,4.0,4.0,2.0,7.0,35,39

In [16]:
dff.mode()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,AMC Gremlin,14.0,8,97.0,95.0,2130.0,15.5,70,US
1,Chevrolet Chevelle Malibu,NaN,NaN,NaN,150.0,3850.0,NaN,NaN,NaN
2,Chevrolet Impala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Datsun PL510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ford Galaxie 500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Plymouth Fury iii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.describe()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
count,407,407.0,407,407.0,407.0,407.0,407.0,407,407
unique,309,131.0,6,84.0,95.0,357.0,97.0,14,4
top,Toyota Corolla,13.0,4,97.0,150.0,2130.0,14.5,73,US
freq,9,20.0,207,22.0,22.0,4.0,23.0,40,254

In [21]:
dff[["MPG","Acceleration"]]

       MPG Acceleration
0   DOUBLE       DOUBLE
1     18.0         12.0
2     15.0         11.5
3     18.0         11.0
4     16.0         12.0
5     17.0         10.5
6     15.0         10.0
7     14.0          9.0
8     14.0          8.5
9     14.0         10.0
10    15.0          8.5
11       0         17.5
12       0         11.5
13       0         11.0
14       0         10.5
15       0         11.0
16    15.0         10.0
17    14.0          8.0
18       0          8.0
19    15.0          9.5
20    14.0         10.0
21    24.0         15.0
22    22.0         15.5
23    18.0         15.5
24    21.0         16.0
25    27.0         14.5
26    26.0         20.5
27    25.0         17.5
28    24.0         14.5
29    25.0         17.5
30    26.0         12.5
31    21.0         15.0
32    10.0         14.0
33    10.0         15.0
34    11.0         13.5
35     9.0         18.5
36    27.0         14.5
37    28.0         15.5
38    25.0         14.0
39    25.0         19.0
40       0         20.0
41    19.0         13.0
42    16.0         15.5
43    17.0         15.5
44    19.0         15.5
45    18.0         15.5
46    14.0         12.0
47    14.0         11.5
48    14.0         13.5
49    14.0         13.0
50    12.0         11.5

In [22]:
df.count()

Car             407
MPG             407
Cylinders       407
Displacement    407
Horsepower      407
Weight          407
Acceleration    407
Model           407
Origin          407
dtype: int64

In [23]:
dff.count()

Car             51
MPG             51
Cylinders       51
Displacement    51
Horsepower      51
Weight          51
Acceleration    51
Model           51
Origin          51
dtype: int64

In [43]:
dff["Model"].mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of 0     INT
1      70
2      70
3      70
4      70
5      70
6      70
7      70
8      70
9      70
10     70
11     70
12     70
13     70
14     70
15     70
16     70
17     70
18     70
19     70
20     70
21     70
22     70
23     70
24     70
25     70
26     70
27     70
28     70
29     70
30     70
31     70
32     70
33     70
34     70
35     70
36     71
37     71
38     71
39     71
40     71
41     71
42     71
43     71
44     71
45     71
46     71
47     71
48     71
49     71
50     71
Name: Model, dtype: object>

In [48]:
dff

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,STRING,DOUBLE,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,CAT
1,Chevrolet Chevelle Malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US
2,Buick Skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US
3,Plymouth Satellite,18.0,8,318.0,150.0,3436.0,11.0,70,US
4,AMC Rebel SST,16.0,8,304.0,150.0,3433.0,12.0,70,US
5,Ford Torino,17.0,8,302.0,140.0,3449.0,10.5,70,US
6,Ford Galaxie 500,15.0,8,429.0,198.0,4341.0,10.0,70,US
7,Chevrolet Impala,14.0,8,454.0,220.0,4354.0,9.0,70,US
8,Plymouth Fury iii,14.0,8,440.0,215.0,4312.0,8.5,70,US
9,Pontiac Catalina,14.0,8,455.0,225.0,4425.0,10.0,70,US
10,AMC Ambassador DPL,15.0,8,390.0,190.0,3850.0,8.5,70,US
11,Citroen DS-21 Pallas,0,4,133.0,115.0,3090.0,17.5,70,Europe
12,Chevrolet Chevelle Concours (sw),0,8,350.0,165.0,4142.0,11.5,70,US
13,Ford Torino (sw),0,8,351.0,153.0,4034.0,11.0,70,US
14,Plymouth Satellite (sw),0,8,383.0,175.0,4166.0,10.5,70,US
15,AMC Rebel SST (sw),0,8,360.0,175.0,3850.0,11.0,70,US
16,Dodge Challenger SE,15.0,8,383.0,170.0,3563.0,10.0,70,US
17,Plymouth 'Cuda 340,14.0,8,340.0,160.0,3609.0,8.0,70,US
18,Ford Mustang Boss 302,0,8,302.0,140.0,3353.0,8.0,70,US
19,Chevrolet Monte Carlo,15.0,8,400.0,150.0,3761.0,9.5,70,US
20,Buick Estate Wagon (sw),14.0,8,455.0,225.0,3086.0,10.0,70,US
21,Toyota Corolla Mark ii,24.0,4,113.0,95.0,2372.0,15.0,70,Japan
22,Plymouth Duster,22.0,6,198.0,95.0,2833.0,15.5,70,US
23,AMC Hornet,18.0,6,199.0,97.0,2774.0,15.5,70,US
24,Ford Maverick,21.0,6,200.0,85.0,2587.0,16.0,70,US
25,Datsun PL510,27.0,4,97.0,88.0,2130.0,14.5,70,Japan
26,Volkswagen 1131 Deluxe Sedan,26.0,4,97.0,46.0,1835.0,20.5,70,Europe
27,Peugeot 504,25.0,4,110.0,87.0,2672.0,17.5,70,Europe
28,Audi 100 LS,24.0,4,107.0,90.0,2430.0,14.5,70,Europe
29,Saab 99e,25.0,4,104.0,95.0,2375.0,17.5,70,Europe
30,BMW 2002,26.0,4,121.0,113.0,2234.0,12.5,70,Europe
31,AMC Gremlin,21.0,6,199.0,90.0,2648.0,15.0,70,US
32,Ford F250,10.0,8,360.0,215.0,4615.0,14.0,70,US
33,Chevy C20,10.0,8,307.0,200.0,4376.0,15.0,70,US
34,Dodge D200,11.0,8,318.0,210.0,4382.0,13.5,70,US
35,Hi 1200D,9.0,8,304.0,193.0,4732.0,18.5,70,US
36,Datsun PL510,27.0,4,97.0,88.0,2130.0,14.5,71,Japan
37,Chevrolet Vega 2300,28.0,4,140.0,90.0,2264.0,15.5,71,US
38,Toyota Corolla,25.0,4,113.0,95.0,2228.0,14.0,71,Japan
39,Ford Pinto,25.0,4,98.0,0,2046.0,19.0,71,US
40,Volkswagen Super Beetle 117,0,4,97.0,48.0,1978.0,20.0,71,Europe
41,AMC Gremlin,19.0,6,232.0,100.0,2634.0,13.0,71,US
42,Plymouth Satellite Custom,16.0,6,225.0,105.0,3439.0,15.5,71,US
43,Chevrolet Chevelle Malibu,17.0,6,250.0,100.0,3329.0,15.5,71,US
44,Ford Torino 500,19.0,6,250.0,88.0,3302.0,15.5,71,US
45,AMC Matador,18.0,6,232.0,100.0,3288.0,15.5,71,US
46,Chevrolet Impala,14.0,8,350.0,165.0,4209.0,12.0,71,US
47,Pontiac Catalina Brougham,14.0,8,400.0,175.0,4464.0,11.5,71,US
48,Ford Galaxie 500,14.0,8,351.0,153.0,4154.0,13.5,71,US
49,Plymouth Fury iii,14.0,8,318.0,150.0,4096.0,13.0,71,US
50,Dodge Monaco (sw),12.0,8,383.0,180.0,4955.0,11.5,71,US

In [50]:
dff["Car"]

0                               STRING
1            Chevrolet Chevelle Malibu
2                    Buick Skylark 320
3                   Plymouth Satellite
4                        AMC Rebel SST
5                          Ford Torino
6                     Ford Galaxie 500
7                     Chevrolet Impala
8                    Plymouth Fury iii
9                     Pontiac Catalina
10                  AMC Ambassador DPL
11                Citroen DS-21 Pallas
12    Chevrolet Chevelle Concours (sw)
13                    Ford Torino (sw)
14             Plymouth Satellite (sw)
15                  AMC Rebel SST (sw)
16                 Dodge Challenger SE
17                  Plymouth 'Cuda 340
18               Ford Mustang Boss 302
19               Chevrolet Monte Carlo
20             Buick Estate Wagon (sw)
21              Toyota Corolla Mark ii
22                     Plymouth Duster
23                          AMC Hornet
24                       Ford Maverick
25                        Datsun PL510
26        Volkswagen 1131 Deluxe Sedan
27                         Peugeot 504
28                         Audi 100 LS
29                            Saab 99e
30                            BMW 2002
31                         AMC Gremlin
32                           Ford F250
33                           Chevy C20
34                          Dodge D200
35                            Hi 1200D
36                        Datsun PL510
37                 Chevrolet Vega 2300
38                      Toyota Corolla
39                          Ford Pinto
40         Volkswagen Super Beetle 117
41                         AMC Gremlin
42           Plymouth Satellite Custom
43           Chevrolet Chevelle Malibu
44                     Ford Torino 500
45                         AMC Matador
46                    Chevrolet Impala
47           Pontiac Catalina Brougham
48                    Ford Galaxie 500
49                   Plymouth Fury iii
50                   Dodge Monaco (sw)
Name: Car, dtype: object